### ISSUE TITLE
System.InvalidOperationException: Sequence contains no elements

### ISSUE THREAD

**Issue by brianfreud** [jonathanbrecher/sharedclustering#3]
Trying to limit results to only those including my paternal aunt, I entered her ID in the "Filter Test IDs to" field on the Cluster tab.  My aunt is shown (in the 4379 lines of results) when I run the cluster report without any ID to filter.  Including her ID, however, I get the following error, with no results generated:

System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at AncestryDnaClustering.Models.HierarchicalClustering.HierarchicalClustering.<ClusterAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at AncestryDnaClustering.ViewModels.AncestryDnaHierarchicalClusteringViewModel.<ProcessSavedDataAsync>d__83.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AncestryDnaClustering.ViewModels.AncestryDnaHierarchicalClusteringViewModel.<<-ctor>b__7_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jonathanbrecher** [comment]
I'll fix the crash but building a cluster out of one (1) match is never going to be useful. You need to include all of your aunt's matches in the "Filter test IDs to" list as well as your aunt, and ideally all of _their_ matches also...

**Comment by brianfreud** [comment]
Ahh, I misunderstood it to be filtering to any match that would include her ID in their matches.

**Comment by jonathanbrecher** [comment]
Fixed in 1.1.0.69
