### ISSUE TITLE
Exception when additionalMatchesDistinct is empty

### ISSUE THREAD

**Issue by NLFiles** [jonathanbrecher/sharedclustering#4]
An exception is thrown when additionalMatchesDistinct is empty (additionalMatchesDistinct.Count is 0) when clustering a file downloaded from Ancestry.

System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Max(IEnumerable`1 source)
   at SharedClustering.HierarchicalClustering.ClusterExtender.<Recluster>d__7.MoveNext() in C:\Users\files\source\repos\sharedclustering-master\sharedclustering-master\src\SharedClustering.HierarchicalClustering\ClusterExtender.cs:line 131
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at SharedClustering.HierarchicalClustering.ClusterExtender.<MaybeExtendAsync>d__5.MoveNext() in C:\Users\files\source\repos\sharedclustering-master\sharedclustering-master\src\SharedClustering.HierarchicalClustering\ClusterExtender.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SharedClustering.HierarchicalClustering.HierarchicalClusterer.<ClusterAsync>d__11.MoveNext() in C:\Users\files\source\repos\sharedclustering-master\sharedclustering-master\src\SharedClustering.HierarchicalClustering\HierarchicalClusterer.cs:line 152
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AncestryDnaClustering.ViewModels.AncestryDnaHierarchicalClusteringViewModel.<ProcessSavedDataAsync>d__93.MoveNext() in C:\Users\files\source\repos\sharedclustering-master\sharedclustering-master\src\SharedClustering\ViewModels\AncestryDnaHierarchicalClusteringViewModel.cs:line 443
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at AncestryDnaClustering.ViewModels.AncestryDnaHierarchicalClusteringViewModel.<<-ctor>b__8_0>d.MoveNext() in C:\Users\files\source\repos\sharedclustering-master\sharedclustering-master\src\SharedClustering\ViewModels\AncestryDnaHierarchicalClusteringViewModel.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jonathanbrecher** [comment]
Fixed in 1.1.0.118. Sorry about that!

**Comment by NLFiles** [comment]
Thanks.  The program is awesome!
